/**
 * ============================================================
 * debts.js — Debt Form Handler & Debt List Rendering
 * ============================================================
 *
 * Handles:
 *   - Debt form submission (add a new debt / loan)
 *   - Input validation (creditor required, positive amount)
 *   - Building the debt object per CLAUDE.md schema
 *   - Delegating persistence to Storage.addDebt()
 *   - Rendering the debt cards in #debts-grid
 *   - Toggling paid/unpaid status per debt
 *   - Deleting individual debts
 *
 * Depends on (must load first):
 *   - js/storage.js — Storage.addDebt(), Storage.getDebts(),
 *                      Storage.removeDebt()
 *
 * Schema (from CLAUDE.md):
 *   { id, creditor, amount, dueDate, paid, note }
 *
 *   - id:       auto-generated by Storage.addDebt()
 *   - creditor: string — who the debt is owed to
 *   - amount:   number — total debt amount
 *   - dueDate:  string — YYYY-MM-DD (optional)
 *   - paid:     number — amount repaid so far (defaults to 0)
 *   - note:     string — optional note
 *
 * Forms expected in DOM:
 *   #debt-form — <form> with inputs for creditor, amount,
 *                dueDate, and note
 *
 * Bootstrap:
 *   initDebts() is called by js/app.js during the main
 *   application init sequence. Do NOT add a separate
 *   DOMContentLoaded listener here — app.js owns the boot order.
 * ============================================================
 */

const Debts = (() => {
  'use strict';

  // ──────────────────────────────────────────────────────
  // STORAGE RESOLUTION
  // Avoid collision with the browser's built-in
  // window.Storage (Web Storage API).
  // ──────────────────────────────────────────────────────

  const Storage = AphStorage;

  // ──────────────────────────────────────────────────────
  // CSS SELECTORS
  // ──────────────────────────────────────────────────────

  const SEL = Object.freeze({
    FORM:          '#debt-form',
    CREDITOR:      '#debt-creditor',
    AMOUNT:        '#debt-amount',
    DUE_DATE:      '#debt-due-date',
    NOTE:          '#debt-note',
    ERROR_MSG:     '#debt-error',
    FORM_WRAPPER:  '#debt-form-wrapper',
    GRID:          '#debts-grid',
    BTN_ADD:       '#btn-add-debt',
    BTN_CANCEL:    '#debt-cancel',
  });

  // ──────────────────────────────────────────────────────
  // DOM HELPERS
  // ──────────────────────────────────────────────────────

  /**
   * Short-hand for document.querySelector.
   *
   * @param  {string}          selector — CSS selector
   * @return {HTMLElement|null}
   */
  function $(selector) {
    return document.querySelector(selector);
  }

  // ──────────────────────────────────────────────────────
  // VALIDATION
  // ──────────────────────────────────────────────────────

  /**
   * Validate the debt form inputs.
   *
   * Rules:
   *   - creditor must be a non-empty string
   *   - amount must be a positive number (> 0)
   *   - dueDate is optional, but if provided must be a valid date
   *
   * @param  {Object}               data — { creditor, amount, dueDate }
   * @return {{ valid: boolean, errors: string[] }}
   */
  function validateDebt(data) {
    const errors = [];

    // ── Creditor ───────────────────────────────────────
    if (!data.creditor || !data.creditor.trim()) {
      errors.push('Please enter a creditor name.');
    }

    // ── Amount ─────────────────────────────────────────
    const amount = parseFloat(data.amount);
    if (isNaN(amount) || amount <= 0) {
      errors.push('Amount must be a positive number greater than zero.');
    }

    // ── Due date (optional — but must be valid if given)
    if (data.dueDate && isNaN(Date.parse(data.dueDate))) {
      errors.push('Invalid due date format.');
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  }

  // ──────────────────────────────────────────────────────
  // ERROR DISPLAY
  // ──────────────────────────────────────────────────────

  /**
   * Show one or more validation error messages below the form.
   *
   * @param {HTMLElement|null} el     — the error container element
   * @param {string[]}        errors — array of error strings
   */
  function showError(el, errors) {
    if (!el) return;
    el.textContent = errors.join(' ');
    el.classList.remove('hidden');
  }

  /**
   * Hide the error message container.
   *
   * @param {HTMLElement|null} el — the error container element
   */
  function hideError(el) {
    if (!el) return;
    el.textContent = '';
    el.classList.add('hidden');
  }

  // ──────────────────────────────────────────────────────
  // FORM SUBMISSION HANDLER
  // ──────────────────────────────────────────────────────

  /**
   * Handle the debt form submission.
   *
   * Flow:
   *   1. Prevent default form submission (no page reload)
   *   2. Read and sanitise form inputs
   *   3. Validate (creditor required, positive amount)
   *   4. Build debt object matching CLAUDE.md schema
   *   5. Persist via Storage.addDebt()
   *   6. Reset form, hide it, refresh debt list
   *
   * @param {SubmitEvent} e — the form submit event
   */
  function handleDebtFormSubmit(e) {
    e.preventDefault();
    e.stopPropagation();

    console.log('[Debts] handleDebtFormSubmit fired');

    try {
      // Guard: ensure Storage is loaded.
      if (!Storage || typeof Storage.addDebt !== 'function') {
        console.error('[Debts] Storage module not loaded — cannot save debt.');
        const errorEl = $(SEL.ERROR_MSG);
        showError(errorEl, ['Storage unavailable. Please reload the page.']);
        return;
      }

      const form = $(SEL.FORM);
      if (!form) return;

      // ── 1. Read raw inputs ─────────────────────────────
      const creditorInput = $(SEL.CREDITOR);
      const amountInput   = $(SEL.AMOUNT);
      const dueDateInput  = $(SEL.DUE_DATE);
      const noteInput     = $(SEL.NOTE);
      const errorEl       = $(SEL.ERROR_MSG);

      const rawData = {
        creditor: creditorInput ? creditorInput.value : '',
        amount:   amountInput ? amountInput.value : '',
        dueDate:  dueDateInput ? dueDateInput.value : '',
      };

      console.log('[Debts] Form values:', rawData);

      // ── 2. Validate ────────────────────────────────────
      const { valid, errors } = validateDebt(rawData);

      if (!valid) {
        console.warn('[Debts] Validation failed:', errors);
        showError(errorEl, errors);
        return;
      }

      // ── 3. Build debt object ───────────────────────────
      //    Schema: { id, creditor, amount, dueDate, paid, note }
      //    `id` is auto-generated by Storage.addDebt().
      //    `paid` starts at 0 — no repayment yet.
      const debt = {
        creditor: rawData.creditor.trim(),
        amount:   parseFloat(rawData.amount),
        dueDate:  rawData.dueDate || '',
        paid:     0,
        note:     noteInput ? noteInput.value.trim() : '',
      };

      console.log('[Debts] Persisting debt:', debt);

      // ── 4. Persist ─────────────────────────────────────
      Storage.addDebt(debt);

      // ── 5. Reset form & hide it ────────────────────────
      form.reset();
      hideError(errorEl);

      const wrapper = $(SEL.FORM_WRAPPER);
      if (wrapper) wrapper.classList.add('hidden');

      // ── 6. Refresh debt display ────────────────────────
      renderDebtList();

      console.log('[Debts] Debt saved successfully');

    } catch (err) {
      console.error('[Debts] handleDebtFormSubmit error:', err);
      const errorEl = $(SEL.ERROR_MSG);
      showError(errorEl, ['Something went wrong. Please try again.']);
    }
  }

  // ──────────────────────────────────────────────────────
  // FORM — show/hide & event binding
  // ──────────────────────────────────────────────────────

  /**
   * Wire up the debt form: submit handler, cancel button,
   * and "Add Debt" toggle button.
   *
   * Called once by initDebts() during bootstrap.
   */
  function bindDebtForm() {
    const form      = $(SEL.FORM);
    const btnAdd    = $(SEL.BTN_ADD);
    const btnCancel = $(SEL.BTN_CANCEL);
    const wrapper   = $(SEL.FORM_WRAPPER);

    // ── Submit handler ─────────────────────────────────
    if (form) {
      form.addEventListener('submit', handleDebtFormSubmit);
    }

    // ── "Add Debt" button — toggle form visibility ─────
    if (btnAdd && wrapper) {
      btnAdd.addEventListener('click', () => {
        wrapper.classList.toggle('hidden');
      });
    }

    // ── Cancel button — hide form and reset ────────────
    if (btnCancel && wrapper && form) {
      btnCancel.addEventListener('click', () => {
        form.reset();
        const errorEl = $(SEL.ERROR_MSG);
        hideError(errorEl);
        wrapper.classList.add('hidden');
      });
    }
  }

  // ──────────────────────────────────────────────────────
  // DELETE DEBT
  // ──────────────────────────────────────────────────────

  /**
   * Delete a debt by its id and refresh the debt list.
   *
   * @param {string} id — the debt id to delete
   */
  function deleteDebt(id) {
    if (!id) return;
    try {
      Storage.removeDebt(id);
      renderDebtList();
    } catch (err) {
      console.error('[Debts] Failed to delete debt:', err);
    }
  }

  // ──────────────────────────────────────────────────────
  // TOGGLE PAID STATUS
  // ──────────────────────────────────────────────────────

  /**
   * Toggle the paid status of a debt.
   *
   * If the debt is currently unpaid (paid === 0), marks it as
   * fully paid by setting paid = amount. If it is already fully
   * paid, resets paid back to 0.
   *
   * Uses Storage.updateDebt() to perform a partial update on the
   * `aph_debts` collection in localStorage, then re-renders the
   * debt list so the UI reflects the change immediately.
   *
   * @param {string} id — the debt id to toggle
   */
  function toggleDebtPaid(id) {
    if (!id) return;

    try {
      if (!Storage || typeof Storage.updateDebt !== 'function') {
        console.error('[Debts] Storage.updateDebt unavailable.');
        return;
      }

      const debt = Storage.getDebtById(id);
      if (!debt) {
        console.warn('[Debts] Debt not found:', id);
        return;
      }

      const amount  = debt.amount || 0;
      const paid    = debt.paid || 0;
      const isFullyPaid = paid >= amount && amount > 0;

      // Toggle: if fully paid → reset to 0; otherwise → mark fully paid
      const newPaid = isFullyPaid ? 0 : amount;

      Storage.updateDebt(id, { paid: newPaid });
      console.log('[Debts] Toggled paid:', id, '| paid:', newPaid);

      renderDebtList();
    } catch (err) {
      console.error('[Debts] Failed to toggle paid status:', err);
    }
  }

  // ──────────────────────────────────────────────────────
  // RENDER — DEBT CARDS
  // ──────────────────────────────────────────────────────

  /**
   * Render all saved debts as cards in #debts-grid.
   *
   * Each card shows:
   *   - Creditor name
   *   - Total amount / paid so far
   *   - Remaining balance
   *   - Due date (if set)
   *   - Note (if set)
   *   - Paid toggle button → marks debt as paid/unpaid
   *   - Delete button → removes the debt
   *
   * After rendering, click handlers are bound to every toggle
   * and delete button.
   */
  function renderDebtList() {
    const gridEl = $(SEL.GRID);
    if (!gridEl) return;

    const debts = Storage.getDebts();

    // ── Empty state ────────────────────────────────────
    if (!debts || debts.length === 0) {
      gridEl.innerHTML = `
        <p class="col-span-full p-12 text-center text-sm leading-loose text-ink-muted"
           data-i18n="no_debts">
          No debts recorded. Add a debt to start tracking repayments.
        </p>`;
      return;
    }

    // ── Sort by due date (soonest first, undated last) ─
    const sorted = [...debts].sort((a, b) => {
      if (!a.dueDate && !b.dueDate) return 0;
      if (!a.dueDate) return 1;
      if (!b.dueDate) return -1;
      return a.dueDate.localeCompare(b.dueDate);
    });

    // ── Build cards ────────────────────────────────────
    gridEl.innerHTML = sorted.map(debt => {
      const amount    = debt.amount || 0;
      const paid      = debt.paid || 0;
      const remaining = Math.max(amount - paid, 0);
      const isPaid    = remaining === 0 && amount > 0;

      const borderColor = isPaid ? 'border-income/30' : 'border-surface-dark';
      const statusLabel = isPaid ? 'Paid in full' : `${Utils.formatCurrency(remaining)} left`;
      const statusColor = isPaid ? 'text-income' : 'text-expense';

      // Toggle button styling changes based on paid state
      const toggleBg    = isPaid
        ? 'bg-income text-white hover:bg-income/80'
        : 'bg-surface-dark text-ink-muted hover:bg-surface hover:text-income';
      const toggleIcon  = isPaid
        ? 'fa-solid fa-circle-check'
        : 'fa-regular fa-circle-check';
      const toggleTitle = isPaid ? 'Mark as unpaid' : 'Mark as paid';

      const dueDateStr = debt.dueDate
        ? new Date(debt.dueDate + 'T00:00:00').toLocaleDateString('en-US', {
            year: 'numeric', month: 'short', day: 'numeric',
          })
        : '';

      return `
        <div class="rounded-xl border ${borderColor} bg-surface-card
                    p-5 shadow-sm transition-shadow hover:shadow-md">

          <!-- Header: creditor + toggle + delete -->
          <div class="mb-3 flex items-center justify-between">
            <span class="text-sm font-medium text-ink ${isPaid ? 'line-through opacity-60' : ''}">
              ${escapeHtml(debt.creditor || 'Unknown')}
            </span>
            <div class="flex items-center gap-1">
              <button data-debt-toggle="${debt.id}"
                      class="flex h-7 w-7 items-center justify-center rounded-md
                             transition-colors ${toggleBg}"
                      title="${toggleTitle}">
                <i class="${toggleIcon} text-xs"></i>
              </button>
              <button data-debt-delete="${debt.id}"
                      class="flex h-7 w-7 items-center justify-center rounded-md
                             text-ink-muted transition-colors
                             hover:bg-expense-light hover:text-expense"
                      title="Remove debt">
                <i class="fa-solid fa-trash-can text-xs"></i>
              </button>
            </div>
          </div>

          <!-- Amounts -->
          <div class="mb-2">
            <p class="font-display text-xl ${isPaid ? 'text-income line-through opacity-60' : 'text-ink'}">
              ${Utils.formatCurrency(amount)}
            </p>
            <p class="text-xs ${statusColor} font-medium mt-1">${statusLabel}</p>
          </div>

          <!-- Meta: due date + note -->
          <div class="space-y-1">
            ${dueDateStr ? `<p class="text-xs text-ink-muted">
              <i class="fa-regular fa-calendar mr-1"></i>${escapeHtml(dueDateStr)}
            </p>` : ''}
            ${debt.note ? `<p class="text-xs text-ink-muted truncate">
              ${escapeHtml(debt.note)}
            </p>` : ''}
          </div>
        </div>`;
    }).join('');

    // ── Bind toggle buttons ────────────────────────────
    gridEl.querySelectorAll('[data-debt-toggle]').forEach(btn => {
      btn.addEventListener('click', () => {
        const id = btn.getAttribute('data-debt-toggle');
        if (id) toggleDebtPaid(id);
      });
    });

    // ── Bind delete buttons ────────────────────────────
    gridEl.querySelectorAll('[data-debt-delete]').forEach(btn => {
      btn.addEventListener('click', () => {
        const id = btn.getAttribute('data-debt-delete');
        if (!id) return;

        const confirmed = window.confirm('Remove this debt record?');
        if (!confirmed) return;

        deleteDebt(id);
      });
    });
  }

  // ──────────────────────────────────────────────────────
  // FORMATTING HELPERS
  // ──────────────────────────────────────────────────────

  /**
   * Format a numeric amount with the active currency symbol
   * and thousand separators. Delegates to Utils.formatCurrency().
   *
   * @param  {number} value
   * @return {string}
   */
  function formatAmount(value) {
    return Utils.formatCurrency(value);
  }

  /**
   * Escape HTML special characters to prevent XSS when
   * inserting user-generated content into innerHTML.
   *
   * @param  {string} str
   * @return {string}
   */
  function escapeHtml(str) {
    if (typeof str !== 'string') return '';
    const map = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' };
    return str.replace(/[&<>"']/g, c => map[c]);
  }

  // ──────────────────────────────────────────────────────
  // INITIALISE
  // ──────────────────────────────────────────────────────

  /**
   * Initialise all debt-related UI and data rendering.
   *
   * Called once by js/app.js during the main application
   * bootstrap. Sets up:
   *   - Debt form (submit handler, toggle, cancel)
   *   - Initial render of the debt list
   */
  function initDebts() {
    bindDebtForm();
    renderDebtList();
    console.log('[Debts] initDebts complete');
  }

  // ──────────────────────────────────────────────────────
  // PUBLIC API
  // ──────────────────────────────────────────────────────

  return Object.freeze({
    initDebts,
    renderDebtList,
    deleteDebt,
    toggleDebtPaid,
    validateDebt,
  });
})();
