/**
 * ============================================================
 * goals.js — Savings Goal Form Handler & Goal List Rendering
 * ============================================================
 *
 * Handles:
 *   - Goal form submission (add a new savings goal)
 *   - Input validation (name required, positive target amount)
 *   - Building the goal object per CLAUDE.md schema
 *   - Delegating persistence to Storage.addGoal()
 *   - Rendering the goal cards in #goals-grid
 *   - Adding funds to individual goals (update savedAmount)
 *   - Deleting individual goals
 *
 * Depends on (must load first):
 *   - js/storage.js — Storage.addGoal(), Storage.getGoals(),
 *                      Storage.removeGoal(), Storage.updateGoal()
 *
 * Schema (from CLAUDE.md):
 *   { id, name, targetAmount, savedAmount, deadline }
 *
 *   - id:           auto-generated by Storage.addGoal()
 *   - name:         string — goal name (e.g. "Emergency Fund")
 *   - targetAmount: number — savings target
 *   - savedAmount:  number — amount saved so far (defaults to 0)
 *   - deadline:     string — YYYY-MM-DD (optional)
 *
 * Forms expected in DOM:
 *   #goal-form — <form> with inputs for name, targetAmount,
 *                and deadline
 *
 * Bootstrap:
 *   initGoals() is called by js/app.js during the main
 *   application init sequence. Do NOT add a separate
 *   DOMContentLoaded listener here — app.js owns the boot order.
 * ============================================================
 */

const Goals = (() => {
  'use strict';

  // ──────────────────────────────────────────────────────
  // STORAGE RESOLUTION
  // Avoid collision with the browser's built-in
  // window.Storage (Web Storage API).
  // ──────────────────────────────────────────────────────

  const Storage = AphStorage;

  // ──────────────────────────────────────────────────────
  // CSS SELECTORS
  // ──────────────────────────────────────────────────────

  const SEL = Object.freeze({
    FORM:          '#goal-form',
    NAME:          '#goal-name',
    TARGET:        '#goal-target',
    DEADLINE:      '#goal-deadline',
    ERROR_MSG:     '#goal-error',
    FORM_WRAPPER:  '#goal-form-wrapper',
    GRID:          '#goals-grid',
    BTN_ADD:       '#btn-add-goal',
    BTN_CANCEL:    '#goal-cancel',
  });

  // ──────────────────────────────────────────────────────
  // DOM HELPERS
  // ──────────────────────────────────────────────────────

  /**
   * Short-hand for document.querySelector.
   *
   * @param  {string}          selector — CSS selector
   * @return {HTMLElement|null}
   */
  function $(selector) {
    return document.querySelector(selector);
  }

  // ──────────────────────────────────────────────────────
  // VALIDATION
  // ──────────────────────────────────────────────────────

  /**
   * Validate the goal form inputs.
   *
   * Rules:
   *   - name must be a non-empty string
   *   - targetAmount must be a positive number (> 0)
   *   - deadline is optional, but if provided must be a valid date
   *
   * @param  {Object}               data — { name, targetAmount, deadline }
   * @return {{ valid: boolean, errors: string[] }}
   */
  function validateGoal(data) {
    const errors = [];

    // ── Name ───────────────────────────────────────────
    if (!data.name || !data.name.trim()) {
      errors.push('Please enter a goal name.');
    }

    // ── Target amount ──────────────────────────────────
    const target = parseFloat(data.targetAmount);
    if (isNaN(target) || target <= 0) {
      errors.push('Target amount must be a positive number greater than zero.');
    }

    // ── Deadline (optional — but must be valid if given)
    if (data.deadline && isNaN(Date.parse(data.deadline))) {
      errors.push('Invalid deadline format.');
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  }

  // ──────────────────────────────────────────────────────
  // ERROR DISPLAY
  // ──────────────────────────────────────────────────────

  /**
   * Show one or more validation error messages below the form.
   *
   * @param {HTMLElement|null} el     — the error container element
   * @param {string[]}        errors — array of error strings
   */
  function showError(el, errors) {
    if (!el) return;
    el.textContent = errors.join(' ');
    el.classList.remove('hidden');
  }

  /**
   * Hide the error message container.
   *
   * @param {HTMLElement|null} el — the error container element
   */
  function hideError(el) {
    if (!el) return;
    el.textContent = '';
    el.classList.add('hidden');
  }

  // ──────────────────────────────────────────────────────
  // FORM SUBMISSION HANDLER
  // ──────────────────────────────────────────────────────

  /**
   * Handle the goal form submission.
   *
   * Flow:
   *   1. Prevent default form submission (no page reload)
   *   2. Read and sanitise form inputs
   *   3. Validate (name required, positive target amount)
   *   4. Build goal object matching CLAUDE.md schema
   *   5. Persist via Storage.addGoal()
   *   6. Reset form, hide it, refresh goal list
   *
   * @param {SubmitEvent} e — the form submit event
   */
  function handleGoalFormSubmit(e) {
    e.preventDefault();
    e.stopPropagation();

    console.log('[Goals] handleGoalFormSubmit fired');

    try {
      // Guard: ensure Storage is loaded.
      if (!Storage || typeof Storage.addGoal !== 'function') {
        console.error('[Goals] Storage module not loaded — cannot save goal.');
        const errorEl = $(SEL.ERROR_MSG);
        showError(errorEl, ['Storage unavailable. Please reload the page.']);
        return;
      }

      const form = $(SEL.FORM);
      if (!form) return;

      // ── 1. Read raw inputs ─────────────────────────────
      const nameInput     = $(SEL.NAME);
      const targetInput   = $(SEL.TARGET);
      const deadlineInput = $(SEL.DEADLINE);
      const errorEl       = $(SEL.ERROR_MSG);

      const rawData = {
        name:         nameInput ? nameInput.value : '',
        targetAmount: targetInput ? targetInput.value : '',
        deadline:     deadlineInput ? deadlineInput.value : '',
      };

      console.log('[Goals] Form values:', rawData);

      // ── 2. Validate ────────────────────────────────────
      const { valid, errors } = validateGoal(rawData);

      if (!valid) {
        console.warn('[Goals] Validation failed:', errors);
        showError(errorEl, errors);
        return;
      }

      // ── 3. Build goal object ───────────────────────────
      //    Schema: { id, name, targetAmount, savedAmount, deadline }
      //    `id` is auto-generated by Storage.addGoal().
      //    `savedAmount` starts at 0 — no progress yet.
      const goal = {
        name:         rawData.name.trim(),
        targetAmount: parseFloat(rawData.targetAmount),
        savedAmount:  0,
        deadline:     rawData.deadline || '',
      };

      console.log('[Goals] Persisting goal:', goal);

      // ── 4. Persist ─────────────────────────────────────
      Storage.addGoal(goal);

      // ── 5. Reset form & hide it ────────────────────────
      form.reset();
      hideError(errorEl);

      const wrapper = $(SEL.FORM_WRAPPER);
      if (wrapper) wrapper.classList.add('hidden');

      // ── 6. Refresh goal display ────────────────────────
      renderGoalList();

      console.log('[Goals] Goal saved successfully');

    } catch (err) {
      console.error('[Goals] handleGoalFormSubmit error:', err);
      const errorEl = $(SEL.ERROR_MSG);
      showError(errorEl, ['Something went wrong. Please try again.']);
    }
  }

  // ──────────────────────────────────────────────────────
  // FORM — show/hide & event binding
  // ──────────────────────────────────────────────────────

  /**
   * Wire up the goal form: submit handler, cancel button,
   * and "New Goal" toggle button.
   *
   * Called once by initGoals() during bootstrap.
   */
  function bindGoalForm() {
    const form      = $(SEL.FORM);
    const btnAdd    = $(SEL.BTN_ADD);
    const btnCancel = $(SEL.BTN_CANCEL);
    const wrapper   = $(SEL.FORM_WRAPPER);

    // ── Submit handler ─────────────────────────────────
    if (form) {
      form.addEventListener('submit', handleGoalFormSubmit);
    }

    // ── "New Goal" button — toggle form visibility ─────
    if (btnAdd && wrapper) {
      btnAdd.addEventListener('click', () => {
        wrapper.classList.toggle('hidden');
      });
    }

    // ── Cancel button — hide form and reset ────────────
    if (btnCancel && wrapper && form) {
      btnCancel.addEventListener('click', () => {
        form.reset();
        const errorEl = $(SEL.ERROR_MSG);
        hideError(errorEl);
        wrapper.classList.add('hidden');
      });
    }
  }

  // ──────────────────────────────────────────────────────
  // DELETE GOAL
  // ──────────────────────────────────────────────────────

  /**
   * Delete a goal by its id and refresh the goal list.
   *
   * @param {string} id — the goal id to delete
   */
  function deleteGoal(id) {
    if (!id) return;
    try {
      Storage.removeGoal(id);
      renderGoalList();
    } catch (err) {
      console.error('[Goals] Failed to delete goal:', err);
    }
  }

  // ──────────────────────────────────────────────────────
  // ADD FUNDS TO GOAL
  // ──────────────────────────────────────────────────────

  /**
   * Prompt the user for an amount and add it to a goal's
   * savedAmount.
   *
   * Flow:
   *   1. Look up the goal by id via Storage.getGoalById()
   *   2. Prompt the user for a deposit amount (window.prompt)
   *   3. Validate: must be a positive number
   *   4. Compute new savedAmount = current + deposit
   *   5. Persist via Storage.updateGoal(id, { savedAmount })
   *   6. Re-render the goal list
   *
   * @param {string} id — the goal id to add funds to
   */
  function addFundsToGoal(id) {
    if (!id) return;

    try {
      if (!Storage || typeof Storage.updateGoal !== 'function') {
        console.error('[Goals] Storage.updateGoal unavailable.');
        return;
      }

      const goal = Storage.getGoalById(id);
      if (!goal) {
        console.warn('[Goals] Goal not found:', id);
        return;
      }

      const goalName = goal.name || 'Untitled Goal';
      const current  = goal.savedAmount || 0;
      const target   = goal.targetAmount || 0;

      // ── Prompt for amount ─────────────────────────────
      const input = window.prompt(
        `Add funds to "${goalName}"\nCurrent: ${Utils.formatCurrency(current)} / ${Utils.formatCurrency(target)}\n\nEnter amount to add:`
      );

      // User cancelled the prompt
      if (input === null) return;

      // ── Validate ──────────────────────────────────────
      const amount = parseFloat(input);

      if (isNaN(amount) || amount <= 0) {
        window.alert('Please enter a positive number greater than zero.');
        return;
      }

      // ── Compute new saved amount ──────────────────────
      const newSaved = current + amount;

      Storage.updateGoal(id, { savedAmount: newSaved });
      console.log('[Goals] Funds added:', id, '| added:', amount, '| new total:', newSaved);

      // ── Re-render ─────────────────────────────────────
      renderGoalList();

    } catch (err) {
      console.error('[Goals] Failed to add funds:', err);
    }
  }

  // ──────────────────────────────────────────────────────
  // RENDER — GOAL CARDS
  // ──────────────────────────────────────────────────────

  /**
   * Render all saved goals as cards in #goals-grid.
   *
   * Each card shows:
   *   - Goal name
   *   - Target amount
   *   - Saved amount with progress bar
   *   - Deadline (if set)
   *   - "Add Funds" button → prompts for deposit amount
   *   - Delete button → removes the goal
   *
   * After rendering, click handlers are bound to every
   * add-funds and delete button.
   */
  function renderGoalList() {
    const gridEl = $(SEL.GRID);
    if (!gridEl) return;

    const goals = Storage.getGoals();

    // ── Empty state ────────────────────────────────────
    if (!goals || goals.length === 0) {
      gridEl.innerHTML = `
        <p class="col-span-full p-12 text-center text-sm leading-loose text-ink-muted"
           data-i18n="no_goals">
          No goals yet. Set a savings goal to start tracking.
        </p>`;
      return;
    }

    // ── Sort by deadline (soonest first, undated last) ─
    const sorted = [...goals].sort((a, b) => {
      if (!a.deadline && !b.deadline) return 0;
      if (!a.deadline) return 1;
      if (!b.deadline) return -1;
      return a.deadline.localeCompare(b.deadline);
    });

    // ── Build cards ────────────────────────────────────
    gridEl.innerHTML = sorted.map(goal => {
      const target     = goal.targetAmount || 0;
      const saved      = goal.savedAmount || 0;
      const percent    = target > 0 ? Math.min(Math.round((saved / target) * 100), 100) : 0;
      const isComplete = saved >= target && target > 0;

      const barColor    = isComplete ? 'bg-income' : 'bg-primary';
      const borderColor = isComplete ? 'border-income/30' : 'border-surface-dark';
      const statusColor = isComplete ? 'text-income' : 'text-primary';
      const statusLabel = isComplete ? 'Goal reached!' : `${percent}% saved`;

      const deadlineStr = goal.deadline
        ? new Date(goal.deadline + 'T00:00:00').toLocaleDateString('en-US', {
            year: 'numeric', month: 'short', day: 'numeric',
          })
        : '';

      return `
        <div class="rounded-xl border ${borderColor} bg-surface-card
                    p-5 shadow-sm transition-shadow hover:shadow-md">

          <!-- Header: name + actions -->
          <div class="mb-3 flex items-center justify-between">
            <span class="text-sm font-medium text-ink ${isComplete ? 'line-through opacity-60' : ''}">
              ${escapeHtml(goal.name || 'Untitled Goal')}
            </span>
            <div class="flex items-center gap-1">
              ${!isComplete ? `
              <button data-goal-add-funds="${goal.id}"
                      class="flex items-center gap-1 rounded-md bg-primary/10
                             px-2 py-1 text-xs font-medium text-primary
                             transition-colors hover:bg-primary/20"
                      title="Add funds">
                <i class="fa-solid fa-plus text-[10px]"></i>
                <span>Add Funds</span>
              </button>` : ''}
              <button data-goal-delete="${goal.id}"
                      class="flex h-7 w-7 items-center justify-center rounded-md
                             text-ink-muted transition-colors
                             hover:bg-expense-light hover:text-expense"
                      title="Remove goal">
                <i class="fa-solid fa-trash-can text-xs"></i>
              </button>
            </div>
          </div>

          <!-- Amounts: saved / target -->
          <div class="mb-3 flex items-baseline justify-between">
            <p class="font-display text-xl ${isComplete ? 'text-income' : 'text-ink'}">
              ${Utils.formatCurrency(saved)}
              <span class="text-sm font-body text-ink-muted">/ ${Utils.formatCurrency(target)}</span>
            </p>
            ${deadlineStr ? `<span class="text-xs text-ink-muted">
              <i class="fa-regular fa-calendar mr-1"></i>${escapeHtml(deadlineStr)}
            </span>` : ''}
          </div>

          <!-- Progress bar track -->
          <div class="mb-2 h-2.5 w-full overflow-hidden rounded-full bg-surface-dark">
            <div class="${barColor} h-full rounded-full transition-all duration-500"
                 style="width: ${percent}%;">
            </div>
          </div>

          <!-- Status label -->
          <p class="text-right text-xs font-medium ${statusColor}">
            ${statusLabel}
          </p>
        </div>`;
    }).join('');

    // ── Bind "Add Funds" buttons ───────────────────────
    gridEl.querySelectorAll('[data-goal-add-funds]').forEach(btn => {
      btn.addEventListener('click', () => {
        const id = btn.getAttribute('data-goal-add-funds');
        if (id) addFundsToGoal(id);
      });
    });

    // ── Bind delete buttons ────────────────────────────
    gridEl.querySelectorAll('[data-goal-delete]').forEach(btn => {
      btn.addEventListener('click', () => {
        const id = btn.getAttribute('data-goal-delete');
        if (!id) return;

        const confirmed = window.confirm('Remove this savings goal?');
        if (!confirmed) return;

        deleteGoal(id);
      });
    });
  }

  // ──────────────────────────────────────────────────────
  // FORMATTING HELPERS
  // ──────────────────────────────────────────────────────

  /**
   * Format a numeric amount with the active currency symbol
   * and thousand separators. Delegates to Utils.formatCurrency().
   *
   * @param  {number} value
   * @return {string}
   */
  function formatAmount(value) {
    return Utils.formatCurrency(value);
  }

  /**
   * Escape HTML special characters to prevent XSS when
   * inserting user-generated content into innerHTML.
   *
   * @param  {string} str
   * @return {string}
   */
  function escapeHtml(str) {
    if (typeof str !== 'string') return '';
    const map = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' };
    return str.replace(/[&<>"']/g, c => map[c]);
  }

  // ──────────────────────────────────────────────────────
  // INITIALISE
  // ──────────────────────────────────────────────────────

  /**
   * Initialise all goal-related UI and data rendering.
   *
   * Called once by js/app.js during the main application
   * bootstrap. Sets up:
   *   - Goal form (submit handler, toggle, cancel)
   *   - Initial render of the goal list
   */
  function initGoals() {
    bindGoalForm();
    renderGoalList();
    console.log('[Goals] initGoals complete');
  }

  // ──────────────────────────────────────────────────────
  // PUBLIC API
  // ──────────────────────────────────────────────────────

  return Object.freeze({
    initGoals,
    renderGoalList,
    deleteGoal,
    addFundsToGoal,
    validateGoal,
  });
})();
